# This script is intended for reading the .txt file generated by 4nec2 containing the power values for
# all slices in azimuth and elevation.
import argparse
import numpy as np
import os


def read_data(filename):
    """Reads the data from the file"""
    unit_conversions = {'Hz': 1, "khz": 1e3, "Mhz": 1e6}
    with open(filename, 'r') as f:
        lines = f.readlines()

    # data has coords (theta, phi) where theta is the elevation angle and phi is the azimuthal angle.
    data = np.zeros([181, 360], dtype=np.float64)
    phis = []
    thetas = []
    phi = 0
    freq_unitless = float(lines[6].split()[2])
    units = lines[6].split()[3]
    freq = freq_unitless * unit_conversions[units]

    for line in lines[10:]:
        fields = line.split()
        if len(fields) == 0:
            # empty line, this is the delimiter between slices of elevation (phi)
            pass
        elif fields[0] == 'Theta':    # Sets the azimuth for the next lines of data
            phi = int(fields[5])
            phis.append(phi)
        elif fields[0] == 'Deg':
            # Skip this line
            pass
        else:
            theta = int(fields[0])
            dbi = float(fields[-1])
            if theta not in thetas:
                thetas.append(theta)
            theta_i = thetas.index(theta)
            phi_i = phis.index(phi)
            data[theta_i, phi_i] = dbi

    return data, np.array(thetas), np.array(phis), freq


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('infile', help="Elevation/Theta .txt file from NEC simulation")
    parser.add_argument('--outfile', help="Resulting .npz file. Defaults to same path as infile with different extension")
    args = parser.parse_args()

    if args.outfile is None:
        outfile = os.path.splitext(args.infile)[0] + '.npz'
    else:
        outfile = args.outfile
    data, thetas, phis, freq = read_data(args.infile)

    np.savez(outfile, data=data, az=phis, el=thetas, freq=freq)
